### ISSUE TITLE
Please add import and export feeds like in foxish.

### ISSUE THREAD

**Issue by pigeonskiller** [davidhampgonsalves/Live-RSS-Bookmarks#15]
Hi, thank you for continuing the development of this very useful extension.
Please add import and export feeds like in foxish.

**Comment by BrianInglis** [comment]
I have a few dozen Foxish Atom/RSS feeds under my Feeds bookmark folder icon. 
Is there any easy way to migrate the setup? 
Shell/sed/gawk/js would be okay: I upgrade ungoogled Chromium from GH/MacChrome/...Chrome using scripts. 
When I try new extension, each feed is duplicated at the end of the Bookmarks bar (visually wrapped onto a vertical menu). 
[That would also be okay but Chrome again double spaced everything (including Windows context menu!). 
Looks like the GSOC amateurs are being allowed to screw around and mess up the UI, to make it easier for the other kiddies on their mobiles; could they maybe just not make any changes to the Desktop UI, unless it is passed by the pro designers? 
Any ideas on how to remove the latest fondleslab regressions?!]

**Comment by davidhampgonsalves** [comment]
I personally use the extension under Brave but it should work with all @BrianInglis
