### ISSUE TITLE
Does NOT work with https://www.videohelp.com/rss/tools

### ISSUE THREAD

**Issue by pigeonskiller** [davidhampgonsalves/Live-RSS-Bookmarks#16]
Hi, thanks for your extension, but I'm sorry to inform you that it does NOT work with VideoHelp RSS at https://www.videohelp.com/rss/tools

**Comment by ninja-gaijin** [comment]
Does not work with https://newalbumreleases.net/feed/ either

**Comment by davidhampgonsalves** [comment]
https://newalbumreleases.net/feed/ is behind cloudflare and sometimes they prompt for human verification which would prevent it from being pulled. 

The extension isn't abandoned but its also just a tool I made for myself so response times will vary.
